---
image: markhobson/maven-chrome:jdk-8

stages:
  # test stages
  - build test
  # prod stages
  - build prod
  # report stages
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

######################## test
build test:
  resource_group: "$CI_COMMIT_REF_SLUG"
  stage: build test
  only:
    - test
  environment:
    name: test
  script:
    - mvn clean
    - mvn compile
    - ./run_tests_for_urls.sh ${URLS} ${testsType}

######################## prod
build prod:
  resource_group: "$CI_COMMIT_REF_SLUG"
  stage: build prod
  when: manual
  only:
    - prod
  environment:
    name: prod
  allow_failure: false
  script:
    - mvn clean
    - mvn compile
    - ./run_tests_for_urls.sh ${URLS} ${testsType}

pages:
  stage: deploy
  environment:
    name: "$CI_COMMIT_REF_SLUG"
  script:
    - ls
    - echo $CI_COMMIT_REF_SLUG
    - ./prepare_reports_for_urls.sh $CI_PIPELINE_ID ${URLS}
    - ls public/$CI_PIPELINE_ID
    - ls target/site/allure-maven-plugin/
  when: on_success
  artifacts:
    expire_in: 7 days
    name: "$CI_PIPELINE_ID"
    paths:
      - public